### ISSUE TITLE
Utility classes are not being generated

### ISSUE THREAD

**Issue by hollandThomas** [cwsdigital/tailwind-utopia#7]
Hey, thanks for this plugin :)

With the current versions of `tailwindcss` and `tailwind-utopia` installed

```json
{
  "dependencies": {
    "tailwind-utopia": "github:cwsdigital/tailwind-utopia#v1.0.5",
    "tailwindcss": "^3.0.24"
  }
}
```

and using the default configuration in `tailwind.config.js`

```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: [],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [require('tailwind-utopia')],
};
```

when running the tailwind jit compiler, all the necessary custom properties seem to be set on `:root` but adding utilities like `ml-l` does not seem to have any effect. There is no `.ml-l {  /* ... */ }` added to the generated `tailwind.css`. The defaults such as `ml-4` do work. Any idea why that might be?

```css
:root {
  --text-size-step--2: calc( ((14.583333333333334 / 16) * 1rem) + (15.36 - 14.583333333333334) * var(--fluid-bp) );
  --text-size-step--1: calc( ((17.5 / 16) * 1rem) + (19.2 - 17.5) * var(--fluid-bp) );
  --text-size-step-0: calc( ((21 / 16) * 1rem) + (24 - 21) * var(--fluid-bp) );
  --text-size-step-1: calc( ((25.2 / 16) * 1rem) + (30 - 25.2) * var(--fluid-bp) );
  --text-size-step-2: calc( ((30.24 / 16) * 1rem) + (37.5 - 30.24) * var(--fluid-bp) );
  --text-size-step-3: calc( ((36.288 / 16) * 1rem) + (46.875 - 36.288) * var(--fluid-bp) );
  --text-size-step-4: calc( ((43.5456 / 16) * 1rem) + (58.59375 - 43.5456) * var(--fluid-bp) );
  --text-size-step-5: calc( ((52.254719999999985 / 16) * 1rem) + (73.2421875 - 52.254719999999985) * var(--fluid-bp) );
  --fs-3xs: calc( 0.328125rem + (6 - 5.25) * var(--fluid-bp) );
  --fs-2xs: calc( 0.65625rem + (12 - 10.5) * var(--fluid-bp) );
  --fs-xs: calc( 0.984375rem + (18 - 15.75) * var(--fluid-bp) );
  --fs-s: calc( 1.3125rem + (24 - 21) * var(--fluid-bp) );
  --fs-m: calc( 1.96875rem + (36 - 31.5) * var(--fluid-bp) );
  --fs-l: calc( 2.625rem + (48 - 42) * var(--fluid-bp) );
  --fs-xl: calc( 3.9375rem + (72 - 63) * var(--fluid-bp) );
  --fs-2xl: calc( 5.25rem + (96 - 84) * var(--fluid-bp) );
  --fs-3xl: calc( 7.875rem + (144 - 126) * var(--fluid-bp) );
  --fs-3xs-2xs: calc( 0.328125rem + (12 - 5.25) * var(--fluid-bp) );
  --fs-2xs-xs: calc( 0.65625rem + (18 - 10.5) * var(--fluid-bp) );
  --fs-xs-s: calc( 0.984375rem + (24 - 15.75) * var(--fluid-bp) );
  --fs-s-m: calc( 1.3125rem + (36 - 21) * var(--fluid-bp) );
  --fs-m-l: calc( 1.96875rem + (48 - 31.5) * var(--fluid-bp) );
  --fs-l-xl: calc( 2.625rem + (72 - 42) * var(--fluid-bp) );
  --fs-xl-2xl: calc( 3.9375rem + (96 - 63) * var(--fluid-bp) );
  --fs-2xl-3xl: calc( 5.25rem + (144 - 84) * var(--fluid-bp) );
}

.ml-4 {
  margin-left: 1rem;
}
```
